### ISSUE TITLE
which version of opencv would pass compliation?

### ISSUE THREAD

**Issue by EthanGuan** [FORTH-ModelBasedTracker/PyOpenPose#1]
I am using opencv 2.4.11, it's not work. Do you use opencv 3?

**Comment by padeler** [comment]
You need opencv3 if you build openpose with opencv3, but it should work with 2.4.9 as well (although I have not tested it).

**Comment by EthanGuan** [comment]
I build openpose with opencv2.4, it's work.
But it won't pass compliation with your job, could you fix it?

**Comment by padeler** [comment]
I just compiled pyopenpose with opencv2.4 (ubuntu 16.04 default version is 2.4.9) and it is building just fine. 

Could you be a little more specific?

**Comment by EthanGuan** [comment]
`/usr/bin/cmake: /home/guanjiexiong/anaconda2/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 75%] Building CXX object PyOpenPoseLib/CMakeFiles/PyOpenPose.dir/opencv_expose.cpp.o
/home/guanjiexiong/PyOpenPose/PyOpenPoseLib/opencv_expose.cpp:96:5: error: ‘UMatData’ does not name a type
     UMatData* allocate(PyObject* o, int dims, const int* sizes, int type, size_
     ^
/home/guanjiexiong/PyOpenPose/PyOpenPoseLib/opencv_expose.cpp:109:5: error: ‘UMatData’ does not name a type
     UMatData* allocate(int dims0, const int* sizes, int type, void* data, size_
     ^
/home/guanjiexiong/PyOpenPose/PyOpenPoseLib/opencv_expose.cpp:138:19: error: ‘UMatData’ has not been declared
     bool allocate(UMatData* u, int accessFlags, UMatUsageFlags usageFlags) cons`

**Comment by EthanGuan** [comment]
well, I just paste top lines of report. It says 'UMatData' does not name a type

**Comment by padeler** [comment]
Hmm you are correct. This is opencv3 specific. Please disregard my last comment on building with 2.4, turns out I was still using opencv3x includes in my makefiles when i tested it. 

Unfortunately I don't have time to port this back to opencv2.x. So you will need to build with opencv3 in order to use PyOpenPose.

I'll update the requirements in the readme to note that opencv3 is required.
